version: '3'
services:

    web:
        build: .
        ports:
            - "9000:8080"
        depends_on:
            - "redis"
        command: ["./bin/wait-for.sh", "redis:6379", "--", "/bin/server"]
        logging:
            driver: "json-file"
            options:
                labels: "servicename"
                tag: "//"
                max-size: "100m"
                max-file: "10"
    redis:
        image: "redis:alpine"

